version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=smarteoadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smarteodb
    ports:
      - '5432:5432'
    volumes:
      - postgresdb:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  smarteo:
    build:
      context: .
    ports:
      - '8081:8081'
volumes:
  postgresdb:
    driver: local